version: 2
jobs:
  unit-test:
    macos:
      xcode: "11.4.1"
    steps:
      - checkout
      - run:
          name: Install Gems
          command: |
            bundle install --path vendor/bundle
            if (brew outdated | grep carthage > /dev/null); then brew upgrade carthage; fi
      - run:
          name: Run Danager
          command: bundle exec danger
      - restore_cache:
          key: carthage-v1--{{ checksum "Cartfile.resolved" }}
      - run:
          name: Carthage
          command: ./bin/bootstrap-if-needed
      - save_cache:
          key: carthage-v1--{{ checksum "Cartfile.resolved" }}
          paths:
            - "./Carthage"
      - run:
          name: execute tests
          command: |
            mkdir -p ~/test-results/xctest/
            bundle exec fastlane scan --scheme "Unleash iOS" --device "iPhone X" --clean --output_directory="~/test-results/xctest/" --output_types="junit" --output_files="junit.xml" --code_coverage
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml
workflows:
  version: 2
  build-workflow:
    jobs:
      - swiftlint
      - unit-test:
          requires:
            - swiftlint
