version: 2
jobs:
  unit-test:
    macos:
      xcode: "10.2.0"
    steps:
      - checkout
      - restore_cache:
          key: carthage-v1--{{ checksum "Cartfile.resolved" }}
      - run:
          name: Carthage
          command: ./bin/bootstrap-if-needed
      - save_cache:
          key: carthage-v1--{{ checksum "Cartfile.resolved" }}
          paths:
            - "./Carthage"
      - run:
          name: execute tests
          command: |
            mkdir -p ~/test-results/xctest/
            fastlane scan --scheme "Unleash" --device "iPhone X" --clean --output_directory="~/test-results/xctest/" --output_types="junit" --output_files="junit.xml"
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml
workflows:
  version: 2
  build-workflow:
    jobs:
      - swiftlint
      - unit-test:
          requires:
            - swiftlint
